### ISSUE TITLE
Постоянный токен сессии 

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#16]
Нужен постоянный токен сессии чтобы исправить такую ситуацию: одновременные запросы от клиента отпавляясь с правильным токеном, когда первый запрос выполнен, он изменяет токен сессии, и ко времени подлета второго запроса его токен уже недействителен.

**Comment by artemdigi** [comment]
в каких случая клиент будет отправлять так быстро несколько запросов?

**Comment by alexey2baranov** [comment]
Напимер в тестах, когда нужно сразу нескольких копников через ОРМ
загрузить.
[1,2,3].map(each=>Kopnik.load(each))

Или внутри разных тестов чисто случайно совпадает, потому что тесты
проходят в разных потоках параллельно.

вс, 15 дек. 2019 г., 16:14 Artem Digi <notifications@github.com>:

**Comment by artemdigi** [comment]
тести
