### ISSUE TITLE
Генератор фикстур не работает <iso8601("1978-12-09T10:10:29+0000")>

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#20]
Выдает ошибку

>  Could not convert PHP value '1976-06-09T10:40:06+0000' of type 'string' to type 'datetime'. Expected one of the following types: null, DateTime

**Comment by artemdigi** [comment]
createdAt: '<dateTimeBetween("2020-01-03 12:00", "2020-01-03 12:00")>'

**Comment by alexey2baranov** [comment]
отказался от рандомных дат вовсе
