### ISSUE TITLE
Добавить метод GET api/logout

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#24]

**Comment by artemdigi** [comment]
изменил /logout на /api/logout

**Comment by alexey2baranov** [comment]
https://dev.kopnik.org/api/logout
Попробовал с телефона. Не работает

**Comment by artemdigi** [comment]
да, была ошибка, выгрузил фикс

**Comment by alexey2baranov** [comment]
http://localhost:8082/api/logout
по прежнему выдает главную страницу. Должен выдавать ничто. Без всяких редиректов и прочего. 
https://github.com/kopnik-org/kopnik-client/blob/master/doc/auth.md#get-apilogout
