### ISSUE TITLE
Добавить поле locale

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#25]
Добавить копнику поле locale, которое будет показывать на каком языке ему отображается пользовательский интерфейс. Например, ru, en ....

**Comment by artemdigi** [comment]
готово, пока просто хранится поле и на сервере нигде не учитывается

**Comment by artemdigi** [comment]
на сервере нужны будут коды языков ru, en .... а не их полные названия, например Руский, English....

**Comment by alexey2baranov** [comment]
Это должна быть строка, которая отдается вместе с users/get

А вот что в ней хранится, я в другой ишушьке лучше опишу, чтобы здесь все в одной не мешать.

**Comment by artemdigi** [comment]
так и сделал т.е. сейчас  можешь там хранить любую строку

но в сф локали называются ru, en ....

**Comment by alexey2baranov** [comment]
Нормально. На vue.js так же называются

пн, 17 февр. 2020 г., 19:43 Artem Digi <notifications@github.com>:
