### ISSUE TITLE
Страница "Мой профиль"

### ISSUE THREAD

**Issue by kopnik-org** [kopnik-org/kopnik-server#3]
**Что есть сейчас**
Страница https://dev.kopnik.org/geolocation/ устанавливает геолокацию пользователя.

**Что должно быть**
Страница /profile в которой задается геолокация, ФИО, год рождения и последние 4 цифры поспорта. 
Если информация в профиле не подтверждена пользователем, разместить блок сообщение где-то об этом. 
Если информация в профиле не заверена заверителем, разместить блок сообщение где-то о необходимости связаться с заверителем и и ВК-аккаунт заверителя.

**Comment by artemdigi** [comment]
ело в том, что на одну страницу это не удобно толкать... предлагаю так сделать: если у юзера не заданы Отчество, Год рождения и Последние 4 цифры паспорта, то редиректить сюда: /profile/, а когда юзер заполнит эти данные, но ещё не укажет местоположение, то редиректить сюда: /profile/geolocation/ 

после чего юзер уже получит возможность посещать другие разделы.

**Comment by kopnik-org** [comment]
Звучит хорошо
