### ISSUE TITLE
GET users/isMessagesFromGroupAllowed

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#32]
Возвращает текущее значение (не из базы данных) для текущего пользователя.

Только для пользователей.

Для анонимов ошибка 401 NotAuthorized

Результат 
true или false

**Comment by artemdigi** [comment]
тестируй

**Comment by alexey2baranov** [comment]
https://vk.com/dev/messages.isMessagesFromGroupAllowed

Попробуй вот этим

**Comment by alexey2baranov** [comment]
И ответ забыл в response завернуть
https://github.com/kopnik-org/kopnik-client/blob/master/doc/api.md#get-usersismessagesfromgroupallowed

**Comment by artemdigi** [comment]
> https://vk.com/dev/messages.isMessagesFromGroupAllowed
> 
> Попробуй вот этим

попробовал, пробуем!
