### ISSUE TITLE
Роут /test/setupDb

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#34]
Роут, при вызове которого сбрасывается база, как при ручном вызове 

make test-up-with-db-migrations

**Comment by alexey2baranov** [comment]
Все работает, но ты опять забыл ответ в JOSN обернуть и  response присвоить.
Хорошо будет, если весь вывод который сечас тектом прилетает, передашь в response

**Comment by alexey2baranov** [comment]
https://github.com/kopnik-org/kopnik-client/blob/master/doc/test.md#get-apitestsetupdb

**Comment by artemdigi** [comment]
давно уже в response обёрнуто
