### ISSUE TITLE
Добавить пользователям роли (поле role)

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#37]
Поле role для разделения ролей и соответсвующих им полномочий в системе. Тип целое.

```KOPNIK= 1;  DANILOV_KOPNIK= 2; FUTURE_KOPNIK= 3; WOMEN= 4; ALIEN=5```

Обновить связанные с новым полем роуты 
- [x] https://github.com/kopnik-org/kopnik-client/blob/master/doc/api.md#get-apiusersgetids 
- [x] https://github.com/kopnik-org/kopnik-client/blob/master/doc/api.md#post-apiusersupdate

Для вновь созданных пользователей поле role=ALIEN. Поле не может быть null

**Comment by artemdigi** [comment]
очень желательна общая картина, можешь сразу описать какие права у каких ролей будут?

**Comment by alexey2baranov** [comment]
Цель могу сказать только. Цель  - это копное общество. Картина ясная как это все лучше автоматизироать по ходу движения нарисуется.

Первый набросок, который сейчас сформировался такой: 
Во-первых на карте что-то типа бегунка масштаба, только бегунок ролей. С помощью него можно выбрать детальность отображенияю Каждый следующий уровень полноты более полный: Только копных мужей, только копных мужей и подкопных мужей по Данилову, Только копных мужей, подкопных, и стремящихся туда, Только их и женщин, или вообще всех. В зависимости от выбранного уровня, меняется количество отображаемых участников на карте.

Во-вторых, по правам:
1. просматривать карту и ранг копников моут все
2. В беседу 1на1 (кнопка "В ЬЕСЕДУ") могут вызвать все.
3. Копы могут собирать только копные мужи и подкопные (по Данилову). 
4. Старшин могут выбирать только Копные мужи и подкопные (по Данилову)
5. Для роли "Чужой" особые самые ограниченные права. Они могут видеть только маркеры других зарегистрированных пользователей (не фото), ни фамилии, ни ранг, ни звать никого ни в беседу, ни в копу. Вообще ничего кроме карты с маркерами. Возможно "В беседу" разблокируем, это еще подумаем как по-копному правильнее будет.

В целоом все это не первоочередные дела. Поэтому и точного плана пока нет. Сейчас было бы достаточно колонку в БД чтобы эти роли не терялись и потом было с чем работать.

**Comment by alexey2baranov** [comment]
Матрица ролей
https://github.com/kopnik-org/kopnik-client/blob/master/doc/roles.md#%D1%80%D0%BE%D0%BB%D0%B8-%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%BD%D0%B8%D0%BA%D0%BE%D0%B2-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B-kopnikorg

**Comment by artemdigi** [comment]
у незнакомца предлагаю сделать числовое значение = 0, а не 5.

**Comment by artemdigi** [comment]
сделал вот такое соответствие названий и числовых значений

ROLE_STRANGER         = 0
ROLE_KOPNIK           = 1
ROLE_DANILOV_KOPNIK   = 2
ROLE_FUTURE_KOPNIK    = 3
ROLE_FEMALE           = 4

**Comment by alexey2baranov** [comment]
ROLE_STRANGER = 5
