### ISSUE TITLE
Описание десяток (выбора старшины)

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#38]
__Описание процесса__
_Термины и порядок процесса повторяют оригинальный процесс избрания старшины в Копном праве._ 
1. Пользователь с ролью Копный муж, Копный муж по Данилову, стремлюсь стать Копным мужем может выбрать другого копника старшиной. Каким образом он вступает в его десятку.
2. Старшиной может стать Копный муж и Копный муж по Данилову
3. Старшина может быть только один. Если выбирается другой старшина, то предыдущий заменяется новым.
4. Выбор проходит в два шага наподобие "добавить в друзья ВК"  Сначала выбирающий обращается с предложением, что он хочет вступить в десятку, затем выбираемый подтверждает.
5. Только до девяти копников могут быть в десятке одного старшины. Если десятый копник подаёт заявку на вступление в десятку, то старшина не может подтвердить заявку. Сначала он должен исключить кого-то из своей десятки, освободив место.
6. Копник может добровольно выйти из десятки. Для этого не требуется никаких условий.
7. Сообщения о подаче заявки и подтверждении/отклонении заявки, о выходе из десятки отправляются в ВК. Чаты при этом не создаются.

**Comment by artemdigi** [comment]
этот воркфлоу мы уже протестировали ?

**Comment by alexey2baranov** [comment]
Ага. Закрываем
