### ISSUE TITLE
скрыть поле passport в роуте api/users/get для всех пользователей кроме текущего

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#45]

**Comment by artemdigi** [comment]
по коду это давно уже есть... 

https://github.com/kopnik-org/kopnik-server/blob/master/src/Controller/AbstractApiController.php#L47

надо понять как воспроизвести ситуацию, когда распорт уходит "не себе"...

**Comment by alexey2baranov** [comment]
это можно и руками проверить. напрмер зайти под собой и вызвать api/users/get?ids=меня

**Comment by artemdigi** [comment]
напиши тесты для этой задачи

**Comment by alexey2baranov** [comment]
работает. и кстати не совсем прваильно название. прваильно "кроме текущего и кто ожидает заверения у текущего копника"
