### ISSUE TITLE
Неправильно возвращается ошибка (тело см внутри)

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#59]
После удаления (истечения времени жизни) куки SESID прилетает вот такая ошибка. 

nternal Server Error. {"error":{"code":0,"message":"The UserProviderInterface implementation must return an instance of UserInterface, but returned \u0022null\u0022.","file":"\/app\/vendor\/symfony\/security-http\/RememberMe\/TokenBasedRememberMeServices.php","line":53,"trace":[{"file":"\/app\/vendor\/symfony\/security-http\/RememberMe\/AbstractRememberMeServices.php","line":116,"function":"processAutoLoginCookie","class":"Symfony\\Component\\Security\\Http\\RememberMe\\TokenBasedRememberMeServices","type":"-\u003E","args":[["Proxies\\__CG__\\App\\Entity\\User","0JDQu9C10LrRgdC10Lkg0JHQsNGA0LDQvdC+0LI=","1599685705","2d0fc9d75eedbae8079c35caef5edb31f70027a7a8dc606f266b965edf097797"],{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/app\/vendor\/symfony\/security-http\/Firewall\/RememberMeListener.php","line":74,"function":"autoLogin","class":"Symfony\\Component\\Security\\Http\\RememberMe\\AbstractRememberMeServices","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}]},{"file":"\/app\/vendor\/symfony\/security-http\/Firewall\/AbstractListener.php","line":27,"function":"authenticate","class":"Symfony\\Component\\Security\\Http\\Firewall\\RememberMeListener","type":"-\u003E","args":[{}]},{"file":"\/app\/vendor\/symfony\/security-http\/Firewall.php","line":111,"function":"__invoke","class":"Symfony\\Component\\Security\\Http\\Firewall\\AbstractListener","type":"-\u003E","args":[{}]},{"file":"\/app\/vendor\/symfony\/security-http\/Firewall.php","line":84,"function":"callListeners","class":"Symfony\\Component\\Security\\Http\\Firewall","type":"-\u003E","args":[{},{}]},{"file":"\/app\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":270,"function":"onKernelRequest","class":"Symfony\\Component\\Security\\Http\\Firewall","type":"-\u003E","args":[{},"kernel.request",{}]},{"file":"\/app\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":230,"function":"Symfony\\Component\\EventDispatcher\\{closure}","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"::","args":[{},"kernel.request",{}]},{"file":"\/app\/vendor\/symfony\/event-dispatcher\/EventDispatcher.php","line":59,"function":"callListeners","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","args":[[{},{},{},{},{},{},{},{},{},{},{},{},{}],"kernel.request",{}]},{"file":"\/app\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":133,"function":"dispatch","class":"Symfony\\Component\\EventDispatcher\\EventDispatcher","type":"-\u003E","args":[{},"kernel.request"]},{"file":"\/app\/vendor\/symfony\/http-kernel\/HttpKernel.php","line":79,"function":"handleRaw","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1]},{"file":"\/app\/vendor\/symfony\/http-kernel\/Kernel.php","line":196,"function":"handle","class":"Symfony\\Component\\HttpKernel\\HttpKernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}},1,true]},{"file":"\/app\/public\/index.php","line":25,"function":"handle","class":"Symfony\\Component\\HttpKernel\\Kernel","type":"-\u003E","args":[{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers"

**Comment by artemdigi** [comment]
https://stackoverflow.com/questions/38961286/hwi-oauth-remember-me-and-is-authenticated-fully
