### ISSUE TITLE
Не настроено соединение с БД

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#66]
**Как повторить**

1. make down
2. docker volume prune 
3. make up
4. запустить клиент

**Что получаем**

> An exception occurred while executing 'SELECT t0.assurance_chat_invite_link AS assurance_chat_invite_link_1, t0.assurance_chat_id AS assurance_chat_id_2, t0.rank AS rank_3, t0.locale AS locale_4, t0.foreman_request_date AS foreman_request_date_5, t0.last_login_at AS last_login_at_6, t0.confirmed_at AS confirmed_at_7, t0.kopnik_role AS kopnik_role_8, t0.first_name AS first_name_9, t0.last_name AS last_name_10, t0.patronymic AS patronymic_11, t0.photo AS photo_12, t0.small_photo AS small_photo_13, t0.passport_code AS passport_code_14, t0.latitude AS latitude_15, t0.longitude AS longitude_16, t0.status AS status_17, t0.is_witness AS is_witness_18, t0.is_allow_messages_from_community AS is_allow_messages_from_community_19, t0.birth_year AS birth_year_20, t0.id AS id_21, t0.created_at AS created_at_22, t0.foreman_id AS foreman_id_23, t0.foreman_request_id AS foreman_request_id_24, t0.witness_id AS witness_id_25 FROM users t0 WHERE t0.id = ?' with params [2]: SQLSTATE[42P01]: Undefined table: 7 ERROR: relation "users" does not exist LINE 1: ...equest_id_24, t0.witness_id AS witness_id_25 FROM users t0 W... ^ (1500)

**Comment by artemdigi** [comment]
попробуй после docker volume prune запустить

make deploy

**Comment by alexey2baranov** [comment]
а бд теперь называется db_name??
