### ISSUE TITLE
Не работает повторный вход в десятку

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#72]
Баг проявляется когда зашел в десятку, потом вышел, потом опять зашел. Такое возможно, например если одумался человек и его опять приняли. Когда он опять по ссылке, в чат заходит, он туда не попадает.  Висит такое сообщение "Вы были исключены из этой беседы."

Видимо исключение где-то к чату прикреплено, и его надо снимать прежде чем приглашать пользователя повторно. Или вообще на всякий случай снимать, не важно повторно или не повторно он приглашается и только потом присылать ему приглашение заходить.

**Comment by artemdigi** [comment]
это надо искать где-то в вк...

**Comment by alexey2baranov** [comment]
Нет технической возможноси. Рекомендация только такая на этот случай: добавляйте участника десятки в чат десятки вручную.
