### ISSUE TITLE
Ошибка сервера, если пользователя нет в чате десятки в момент исключения из нее 

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#73]
КОгда пользователя нет, и его бот пытается выкинуть, то ВК выдает ошибку. Ее на сервере надо перехватить. Ну нет его в чате и нет. Значит и исключать не надо. Это не надо на клиенты присылать.

Такая ситуация возможна, если например пользователь просто вышел из чата десятки, а потом вспомнил, что в Копнике тоже надо выйти из десятки и вышел.

**Comment by artemdigi** [comment]
проверяй
