### ISSUE TITLE
При смене старшины копник, который произвел смену, не выбрасывается из предыдущего чата десятки

### ISSUE THREAD

**Issue by alexey2baranov** [kopnik-org/kopnik-server#77]
Как повторить
- выбираем одного старшину
- заходим в чат десятки
- выбираем другого старшину

Что должно произойти
- должен исключиться из чата первого старшины

Что происходит
- ничего не происходит. копник так и продолжает сидеть в чате предыдущего старшины

**Comment by artemdigi** [comment]
тестируй
